name: QA
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-lock:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          # Don't cache in this job as we don't install dependencies

      - name: Audit dependencies
        run: pnpm audit --audit-level moderate

  tsc-and-linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run tsc
        run: pnpm run check-types

      - name: Run lint
        run: pnpm run lint

      - name: Check for uncommitted lint changes
        run: git diff --exit-code ./src

      - name: Check Prettier formatting
        run: pnpm run format:check

  jest-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run tests
        run: pnpm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: saleor/saleor-dashboard

  translation-messages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Check message extraction
        run: |
          pnpm run extract-messages
          git diff --exit-code ./locale
