name: Run automation tests on release
on:
  push:

jobs:
  run-tests-on-release:
    uses: ./.github/workflows/run-pw-tests-on-release.yml
    with:
      VERSION: "3.19"
      CUSTOM_VERSION: "3.19.4-5a41d18"
    secrets: inherit